name: CI

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  check:
    name: Compile, run & style-check solutions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Show compiler versions
        run: |
          gcc --version
          g++ --version

      - name: Run checks
        run: bash scripts/ci-check.sh
